### PR TITLE
EC-45245 Ensured teamcity bot is exempted from commit validation

### PR DESCRIPTION
**Pull request by heibroch**
https://jira.visma.com/browse/EC-45245

### CODE REVIEW

**Review by mihaitabamburic — DISMISSED** [review]

**Review by ahe-visma — APPROVED** [review]

**Comment by stefanfinseth** [comment]
I think you need to add qbot to exclusion as well

**Review by nuno-santos-economic — DISMISSED** [review]

**Comment by heibroch** [comment]
> I think you need to add qbot to exclusion as well

It didn't seem necessary, but I can add qbot-app[bot] and deployabot[app] as well if we just want all bots excluded. Thoughts?

**Comment by stefanfinseth** [comment]
> > I think you need to add qbot to exclusion as well
> 
> It didn't seem necessary, but I can add qbot-app[bot] and deployabot[app] as well if we just want all bots excluded. Thoughts?

I think I saw commits from `qbot-app[bot]` on your `zenith-pending-changes` branch as well, so I'd guess those would cause the same issue?

And I think it's fine to let all our bots around the check since anything they merge in from `master` has previously passed the check before reaching `master` in the first place.

**Review by anilcemsimsek-visma — APPROVED** [review]

**Comment by heibroch** [comment]
> > > I think you need to add qbot to exclusion as well
> > 
> > 
> > It didn't seem necessary, but I can add qbot-app[bot] and deployabot[app] as well if we just want all bots excluded. Thoughts?
> 
> I think I saw commits from `qbot-app[bot]` on your `zenith-pending-changes` branch as well, so I'd guess those would cause the same issue?
> 
> And I think it's fine to let all our bots around the check since anything they merge in from `master` has previously passed the check before reaching `master` in the first place.

All bots have now been added.

**Review by anilcemsimsek-visma — APPROVED** [review]

**Pull request merged**
